### ISSUE TITLE
Option to support unquoted control chars in string literals

### ISSUE THREAD

**Issue by ekuleshov** [lrhn/json-tool#4]
I'm porting some Java-based code that used Jackson parser to process json and some of jsons are coming with unquoted  control chars in the string values. E.g.

```
{"foo": "bar
baz"}
```

instead of:

```
{"foo": "bar\nbaz"}
```

Jackson parser has an [ALLOW_UNQUOTED_CONTROL_CHARS](https://fasterxml.github.io/jackson-core/javadoc/2.7/com/fasterxml/jackson/core/JsonParser.Feature.html#ALLOW_UNQUOTED_CONTROL_CHARS) to mitigate such jsons.

It would be great if `json-tool` had something similar.

**Comment by lrhn** [comment]
Unescaped newlines (or any control character) are not valid in [JSON](https://www.json.org/json-en.html#:~:text=A%20string%20is%20a%20sequence) strings. 
You should always be pushing back on the code producing such invalid JSON (read: *not* JSON) first, and try to make them stop.

That said, the `jsontool` parser is *not* a validating parser. It *assumes* input is well-formed JSON, and allows itself to break in wonderful ways if the input isn't (aka. behavior is "unspecified" if input is not valid JSON source). 
In practice it accepts anything that it possibly can, including newlines in strings. The only characters it actually cares about when scanning a string is `\` and `"`. Anything else is silently accepted.

Example:
```dart
import "package:jsontool/jsontool.dart";
void main() {
  var json = JsonReader.fromString("""
"Argle bargle
glop glyf"
""");
  var string = json.expectString(); // Succeeds
  print(string); // Prints "Argle bargle<newline>glop glyf".
}
```
Also works when scanning from UTF-8.

So, the option exists, and you can't turn it off. :grin:

**Comment by ekuleshov** [comment]
> the option exists, and you can't turn it off

You are right. Thank you!
